server:
  port: 8089

# 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
#        # 状态；true = 开启、false 关闭
#        enabled: true
        # redis host
        host: 127.0.0.1
        # redis port
        port: 6379

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml